coverage:
  status:
    project: False
    patch: False

flag_management:
  individual_flags:
    - name: anomaly-detection
      paths:
        - src/
      statuses:
        - type: project
          target: 97%
          threshold: 1%
